[package]
name = "scp"
version = "0.1.0"
edition = "2024"

[dependencies]
agent-client-protocol = "0.4.7"
anyhow.workspace = true
futures = "0.3.31"
jsonrpcmsg = "0.1.2"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
